flags: {}
nix:
  shell-file: shell.nix
packages:
- yi-core
- yi-frontend-vty
#- yi-frontend-pango
- yi-fuzzy-open
- yi-keymap-cua
- yi-keymap-emacs
- yi-keymap-vim
- yi-mode-haskell
- yi-mode-javascript
- yi-mode-brainfuck
- yi-misc-modes
- yi-ireader
- yi-language
- yi-snippet
- yi
extra-deps:
- Hclip-3.0.0.4
- optparse-applicative-0.13.0.0
- vty-5.13
resolver: lts-7.12